### ISSUE TITLE
Uncaught TypeError: Argument 1 passed to PDepend\Source

### ISSUE THREAD

**Issue by JeroenDeDauw** [phpmd/phpmd#372]
```
git clone https://github.com/wmde/FundraisingFrontend.git
cd FundraisingFrontend
git checkout 89a75a4aa02d2457cdb70f796167423011b63767
composer install
php -v
vendor/bin/phpmd --version
```

> PHP 7.0.4-7ubuntu2 (cli) ( NTS )
> PHPMD 2.4.3

    vendor/bin/phpmd tests/ text phpmd.xml

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\AbstractASTNode::addChild() must implement interface PDepend\Source\AST\ASTNode, instance of PDepend\Source\AST\ASTAnonymousClass given, called in /home/j/workspace/FundraisingFrontend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 214 and defined in /home/j/workspace/FundraisingFrontend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTNode.php:367
Stack trace:
#0 /home/j/workspace/FundraisingFrontend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(214): PDepend\Source\AST\AbstractASTNode->addChild(Object(PDepend\Source\AST\ASTAnonymousClass))
#1 /home/j/workspace/FundraisingFrontend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(188): PDepend\Source\Language\PHP\PHPParserVersion70->parseAnonymousClassDeclaration(Object(PDepend\Source\AST\ASTAllocationExpression))
#2 /home/j/workspace/FundraisingFrontend/vend in /home/j/workspace/FundraisingFrontend/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTNode.php on line 367

```

We get this error when running PHPMD against our tests. Not when running against the production code. Presumably this is some PHP7 problem.

**Comment by ravage84** [comment]
@JeroenDeDauw thanks for reporting. As it seems though, the call starts in pdepend. Could you re-open the bug report [there](https://github.com/pdepend/pdepend/issues), please?
