### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by johnwc** [phpmd/phpmd#780]
- PHPMD version: 2.8.2
- PHP Version: 7.3.17
- Installation type: composer
- Operating System / Distribution & Version: 

I am running phpmd in a Azure DevOps pipeline using a ubuntu image, and I am getting this error. The same command runs fine on my local machine, using the same composer install.

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PDepend\Source\AST\AbstractASTCallable::addChild() must implement interface PDepend\Source\AST\ASTNode, null given, called in /home/vsts/work/1/s/src/web/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php on line 183 and defined in /home/vsts/work/1/s/src/web/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php:143
Stack trace:
#0 /home/vsts/work/1/s/src/web/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/PHPParserVersion70.php(183): PDepend\Source\AST\AbstractASTCallable->addChild(NULL)
#1 /home/vsts/work/1/s/src/web/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1265): PDepend\Source\Language\PHP\PHPParserVersion70->parseCallableDeclarationAddition(Object(PDepend\Source\AST\ASTFunction))
#2 /home/vsts/work/1/s/src/web/vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1177): PDepend\Source\Language\PHP\AbstractPHPPars in /home/vsts/work/1/s/src/web/vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/AbstractASTCallable.php on line 143
```

```
PHP 7.3.17-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Apr 19 2020 07:44:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.17, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.17-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.3, Copyright (c) 2002-2020, by Derick Rethans

```

**Comment by tvbeek** [comment]
@johnwc If I read your stack trace I see that it is a bug in PDepend. But still it is strange. You wrote that you instal it with composer, do you use a lock file or is it possible that the used versions are not the same? Is your local PHP version the same as the one on Azure?

**Comment by johnwc** [comment]
@tvbeek  I do have a lock file, so it should be the same as local. Is there a way to get phpmd to verbose or debug log?

**Comment by kylekatarnls** [comment]
```
vendor/pdepend/pdepend/src/main/php/PDepend/Source/Language/PHP/AbstractPHPParser.php(1265): PDepend\Source\Language\PHP\PHPParserVersion70->parseCallableDeclarationAddition(Object(PDepend\Source\AST\ASTFunction))
```

This means it fails trying to parse a closure such as `function () {...}` I don't know if it's a big clue, it depends how often you use closures.

**Comment by tvbeek** [comment]
If you install PHPMD with composer you also have PDepend in vendor/bin/pdepend, With that you can try to run pdepend to see where it failed, example command:  
`vendor/bin/pdepend --debug --summary-xml=summary.xml path/to/scan`

**Comment by johnwc** [comment]
Is there a way to get phpmd to log what directory or file it's sending to pdepend, so that I can pass that to pdepend by itself like you mentioned?

**Comment by AJenbo** [comment]
Looks to work in 3.x, probably solved long before then.
