### ISSUE TITLE
Addressing static array variables entries rise "Avoid using undefined variables" and crashed master

### ISSUE THREAD

**Issue by HLeithner** [phpmd/phpmd#803]
- PHPMD version: 2.8.1
- PHP Version: 7.4.5
- Installation type: composer
- Operating System / Distribution & Version: Debian 11 Bullseye

### Current Behavior
phpmd detect the usage of an undefined variable.

### Expected Behavior
not throwing an error

### Steps To Reproduce:
Use this script:
```php
class Test
{
    public static $staticArray = [];

    public static function showError($parameter)
    {
        echo count(self::$staticArray[$parameter]);
    }
}
``` 
Ends in:
`test.php:9 Avoid using undefined variables such as '$staticArray' which will lead to PHP notices.`

After going thru the checklist I searched for a pullrequest and found out #781 should fix this problem.
But it only fixes the example above, for the real codebase it get even worse checking out `dev-master#8b10c93640b46204401c6bfcb2feb0258a6e2e46` with composer results in:
```
PHP Fatal error:  Uncaught Error: Call to undefined method PDepend\Source\AST\ASTArrayIndexExpression::getNode() in vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/AbstractLocalVariable.php:199
Stack trace:
#0 vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php(218): PHPMD\Rule\AbstractLocalVariable->getVariableImage()
#1 vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/CleanCode/UndefinedVariable.php(80): PHPMD\Rule\CleanCode\UndefinedVariable->checkVariableDefined()
#2 vendor/phpmd/phpmd/src/main/php/PHPMD/RuleSet.php(255): PHPMD\Rule\CleanCode\UndefinedVariable->apply()
#3 vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(259): PHPMD\RuleSet->apply()
#4 vendor/phpmd/phpmd/src/main/php/PHPMD/Parser.php(234): PHPMD\Parser->apply()
#5 vendor/pdepend/pdepend/src/main/php/PDepend/Source/AST/ASTMethod.php(219): PHPMD\Pa in vendor/phpmd/phpmd/src/main/php/PHPMD/Rule/AbstractLocalVariable.php on line 199
```
The advanced example addresses a sub array:
```php
class Test
{
    public static $staticArray = [];

    public static function showError($parameter)
    {
        echo count(self::$staticArray[$parameter]['test']);
    }
}
```

## Checks before submitting
* [x] Be sure that there isn't already an issue about this. See: [Issues list](https://github.com/phpmd/phpmd/issues)
* [x] Be sure that there isn't already a pull request about this. See: [Pull requests](https://github.com/phpmd/phpmd/pulls)
* [x] have added every step to reproduce the bug.
* [x] If possible I added relevant code examples.
* [ ] This issue is about 1 bug and nothing more.
* [x] The issue has a descriptive title. For example:  "JSON rendering failed on Windows for filenames with space".

**Comment by tvbeek** [comment]
@HLeithner thanks for your report, can you check the installed PHP Depend version? It is possible to view that with `composer info pdepend/pdepend` it is possible that there is a newer PHP Depend version that has solved this. PHPMD use this for the parsing.

**Comment by HLeithner** [comment]
Updated to dev-master
```
name     : pdepend/pdepend
descrip. : Official version of pdepend to be handled with Composer
keywords : 
versions : * dev-master, 2.x-dev
type     : library
license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
homepage : 
source   : [git] https://github.com/pdepend/pdepend.git c64472f8e76ca858c79ad9a4cf1e2734b3f8cc38
dist     : [zip] https://api.github.com/repos/pdepend/pdepend/zipball/c64472f8e76ca858c79ad9a4cf1e2734b3f8cc38 c64472f8e76ca858c79ad9a4cf1e2734b3f8cc38
path     : vendor/pdepend/pdepend
names    : pdepend/pdepend
```
But the error is exactly the same.

**Comment by AJenbo** [comment]
Fixed in 3.x

**Comment by HLeithner** [comment]
thanks
