### ISSUE TITLE
Installation via Phive fails if version > 2.7: No GPG Signature

### ISSUE THREAD

**Issue by burzum** [phpmd/phpmd#843]
- PHPMD version: >= 2.8
- PHP Version: 7.4
- Installation type: phar
- Operating System / Distribution & Version: Windows 10

### Current Behavior

```sh
php phive.phar install phpmd/phpmd@2.7
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Linking C:\Users\Florian\.phive\phars/phpmd/phpmd-2.7.0.phar to C:\xampp\htdocs\file-storage\tools/phpmd.bat

php phive.phar install phpmd/phpmd@2.8
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
[WARNING] phpmd/phpmd 2.8.2: No GPG Signature
[WARNING] phpmd/phpmd 2.8.1: No GPG Signature
[WARNING] phpmd/phpmd 2.8.0: No GPG Signature
[WARNING] phpmd/phpmd 2.8.0-beta.2: No GPG Signature
[WARNING] phpmd/phpmd 2.8.0-beta.1: No GPG Signature
[ERROR]   No matching release found!
```

### Expected Behavior

I expect that it installs 2.8 or 2.9 without this problem. It looks like the releases were not signed?

### Steps To Reproduce:

Install phive and just run this:

```sh
php phive.phar install phpmd/phpmd@2.7
```

**Comment by ravage84** [comment]
It's obvious. The newer PHPMD releases, > 2.7.0, have no signed phpmdp.phpar.asc file attached to the release on GitHub.

https://github.com/phpmd/phpmd/releases/tag/2.7.0

![grafik](https://user-images.githubusercontent.com/625761/98451245-41c73880-2144-11eb-884c-988710fe147b.png)

versus the rest:

https://github.com/phpmd/phpmd/releases/tag/2.8.0-beta.1
https://github.com/phpmd/phpmd/releases/tag/2.8.0-beta.2
https://github.com/phpmd/phpmd/releases/tag/2.8.0
https://github.com/phpmd/phpmd/releases/tag/2.8.1
https://github.com/phpmd/phpmd/releases/tag/2.8.2
https://github.com/phpmd/phpmd/releases/tag/2.9.0
https://github.com/phpmd/phpmd/releases/tag/2.9.1

![grafik](https://user-images.githubusercontent.com/625761/98451241-396efd80-2144-11eb-8e22-013f1cc6fd49.png)

I'm going to catch up on that for these rleases, but we should also fix our build @kylekatarnls

**Comment by ravage84** [comment]
I attached the phpmd.phar.asc to the aforementioned releases.

I could download these releases now, but got another error from PHIVE:

````
>php phive.phar install phpmd/phpmd@2.8.0-beta.1
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
[2KDownloading https://api.github.com/repos/phpmd/phpmd/releases 100%0%
[2KDownloading https://github.com/phpmd/phpmd/releases/download/2.8.0-beta.1/phpmd.phar
[2KDownloading https://github.com/phpmd/phpmd/releases/download/2.8.0-beta.1/phpmd.phar.asc
[2K[ERROR]   An error occurred while processing your request:B - 100%0%

          DOMElement::setAttribute(): string is not in UTF-8

          #0 src/shared/PharRegistry.php(31)
          #1 unknown file(0): PharIo\Phive\Cli\Runner->errorHandler()
          #2 src/shared/PharRegistry.php(31): DOMElement->setAttribute()
          #3 src/services/phar/PharService.php(22): PharIo\Phive\PharRegistry->addPhar()
          #4 src/services/phar/InstallService.php(45): PharIo\Phive\PharService->getPharFromRelease()
          #5 src/commands/install/InstallCommand.php(45): PharIo\Phive\InstallService->execute()
          #6 src/commands/install/InstallCommand.php(37): PharIo\Phive\InstallCommand->installRequestedPhar()
          #7 src/shared/cli/Runner.php(215): PharIo\Phive\InstallCommand->execute()
          #8 src/shared/cli/Runner.php(70): PharIo\Phive\Cli\Runner->execute()
          #9 (349): PharIo\Phive\Cli\Runner->run()
          #10 {main}

          Environment: PHP 7.2.1 (on Windows NT 6.1)
          Phive Version: 0.14.4

          This should not have happened and is most likely a bug.
          Please report it at https://github.com/phar-io/phive/issues, make sure you include
          the full output of this error message. Thank you!
````

@burzum can you verify that, please?

**Comment by burzum** [comment]
@ravage84 hmm no. Using Windows 10 and Powershell.

```sh
file-storage-factories [develop ↑3 +1 ~2 -0 !]> php phive.phar install phpmd/phpmd@2.8.0-beta.1
Phive 0.14.4 - Copyright (C) 2015-2020 by Arne Blankerts, Sebastian Heuer and Contributors
Downloading https://api.github.com/rate_limit
Downloading https://github.com/phpmd/phpmd/releases/download/2.8.0-beta.1/phpmd.phar
Downloading https://github.com/phpmd/phpmd/releases/download/2.8.0-beta.1/phpmd.phar.asc
Linking C:\Users\Florian\.phive\phars/phpmd/phpmd-2.8.0-beta.1.phar to C:\xampp\htdocs\file-storage\vendor\phauthentic\file-storage-factories\tools/phpmd.bat

file-storage-factories [develop ↑3 +2 ~3 -0 !]>
```

**Comment by koponk04** [comment]
for the time being, i use `--force-accept-unsigned` option, https://github.com/phar-io/phive/issues/134
hope this help,
